// Drizzle schema barrel. Export every table module from here so both
// `src/db/index.ts` and drizzle-kit (see drizzle.config.ts) pick it up.
//
// ./auth is generated by `pnpm auth:generate`; don't edit it by hand.
export * from "./auth";
export * from "./catalog";
export * from "./orders";
